// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx94t8H7I1Y2dSm_rVwFX0AaF1xLoyqcI',
    appId: '1:490013902588:web:6aa7e476c492c066d4b979',
    messagingSenderId: '490013902588',
    projectId: 'testing-76f97',
    authDomain: 'testing-76f97.firebaseapp.com',
    storageBucket: 'testing-76f97.appspot.com',
    measurementId: 'G-HHG1M9765E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEEzUhsnNtmEAsunME2cFG-3pSCe6C5mc',
    appId: '1:490013902588:android:cbb9466d582603fad4b979',
    messagingSenderId: '490013902588',
    projectId: 'testing-76f97',
    storageBucket: 'testing-76f97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMvIvCMAn6vXHSmF12FZVl1r4FxFfZJe8',
    appId: '1:490013902588:ios:9026ffb85d791d8bd4b979',
    messagingSenderId: '490013902588',
    projectId: 'testing-76f97',
    storageBucket: 'testing-76f97.appspot.com',
    iosBundleId: 'com.example.testing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMvIvCMAn6vXHSmF12FZVl1r4FxFfZJe8',
    appId: '1:490013902588:ios:9026ffb85d791d8bd4b979',
    messagingSenderId: '490013902588',
    projectId: 'testing-76f97',
    storageBucket: 'testing-76f97.appspot.com',
    iosBundleId: 'com.example.testing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAx94t8H7I1Y2dSm_rVwFX0AaF1xLoyqcI',
    appId: '1:490013902588:web:f74db50f4268fd29d4b979',
    messagingSenderId: '490013902588',
    projectId: 'testing-76f97',
    authDomain: 'testing-76f97.firebaseapp.com',
    storageBucket: 'testing-76f97.appspot.com',
    measurementId: 'G-5QY016LT7D',
  );
}
